### ISSUE TITLE
Advanced Lighting Scenes documentation is missing

### ISSUE THREAD

**Issue by MVesovicC4** [control4/docs-driverworks-proxyprotocol#2]
Advanced Lighting Scenes section of the Light_V2 proxy is missing from the documentation. It existed in the DriverWorks SDK OS 3 Proxy and Protocol Guide.

**Comment by jmcgeeverC4** [comment]
I reached out to Brandon Beattie as to why the content was removed. His response: [10/27 4:25 PM] Brandon Beattie
    Not sure.  I do know I've talked to Eldon and ALS API is not something we want to support externally as we change it and we currently have a lot of major improvements in bug/stories.  So if others use it it WILL be broken for them in the future.
​[10/27 4:26 PM] Brandon Beattie
    So the fact that we don't want everyone using ALS and that anyone who uses it should expect their driver to break (plus many parts are OS specific and lua drivers can go into any OS) means it's risky to use
​[10/27 4:27 PM] Brandon Beattie
    Same reason we don't public the proxy<->UI API's as we change these and they are tightly coupled.  
​[10/27 4:27 PM] Brandon Beattie
  If you have specific questions as to what can be used I suggest reaching out ot Brandin directly. Thanks, Jim.

**Comment by MVesovicC4** [comment]
Thanks for the clarification, Jim.
